---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_1
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_1
    name: default
  rollup: true
  scope: model_0
  start_of_day: 0
  superclass: []
  tags: []
  timezone: Asia/Shanghai
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    name: Name
    type: string
  name: Basic
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  - category: []
    index: true
    name: key_1
    type: string
  kind: lookup
  name: Lookup
